"use client";
import { formatLira } from "@/domain/market";
import type { DogHouseSlotRound } from "@/domain/models";
import type { DogHouseLineWin } from "@/domain/slots/dog-house/types";

export function LineWinLabel({line}:{line?:DogHouseLineWin}){if(!line)return null;const calculation=line.wildMultipliers.length>1?`${line.wildMultipliers.map((value)=>`${value}X`).join(" + ")} = ${line.wildMultiplier}X`:`${line.wildMultiplier}X`;return <div className="dogslot-line-label"><small>Линия {line.line} · база {formatLira(line.basePayout)}</small>{line.wildMultiplier>1&&<span>Wild на линии · {calculation}</span>}<strong>{line.wildMultiplier>1?`${line.wildMultiplier}X · `:""}{formatLira(line.payout)}</strong></div>}
export function BonusPickGrid({values,revealed,total}:{values:number[];revealed:number;total:number}){return <div className="dogslot-bonus-pick"><span>CASA DEGLI SPOSI</span><h2>La festa dei cani</h2><strong>{total} GIRI GRATIS</strong><div>{values.map((value,index)=><i className={index<revealed?"is-open":""} key={index}><span>🐾</span><b>{index<revealed?value:""}</b></i>)}</div><small>{revealed<values.length?"Открываем свадебные жетоны…":"Фриспины начинаются"}</small></div>}
export function BigWinOverlay({win,stake,onSkip}:{win:number;stake:number;onSkip:()=>void}){const ratio=win/stake,label=ratio>=100?"FESTA DA CANI!":ratio>=40?"MAGNIFICO!":ratio>=15?"GRANDE!":ratio>=5?"BRAVO!":"VINCITA!";return <button className="dogslot-big-win" onClick={onSkip}><span>{label}</span><strong>{formatLira(win)}</strong><b>{ratio.toLocaleString("ru-RU",{maximumFractionDigits:2})}X ставки</b><small>Нажмите, чтобы ускорить</small></button>}
export function BonusSummary({round,onContinue}:{round:DogHouseSlotRound;onContinue:()=>void}){return <div className="dogslot-summary-v2"><section><span>La festa è finita</span><h2>Собачья свадьба завершена</h2><div><p><small>Фриспинов</small><b>{round.result.awardedFreeSpins}</b></p><p><small>Sticky Wild</small><b>{round.result.stickyWildCount}</b></p><p><small>Лучший множитель</small><b>{round.result.maxLineMultiplier}X</b></p><p><small>Лучший Spin</small><b>{formatLira(round.result.bestFreeSpin)}</b></p></div><p className="dogslot-summary-prize"><small>Выигрыш бонуса</small><strong>{formatLira(round.bonusWin)}</strong><span>Весь раунд · {formatLira(round.totalWin)}</span></p><button onClick={onContinue}>Забрать выигрыш</button></section></div>}
export function BonusAnticipation({active}:{active:boolean}){return active?<div className="dogslot-anticipation" aria-hidden="true"><i>🐾</i><i>🐾</i><span>Ещё одна лапа…</span></div>:null}
