"use client";
import { useCallback, useState } from "react";
import type { DogHouseSpeed } from "../animation/animation-types";
import { createDisplayModel } from "../animation/display-reels";
import { useDogHousePlayback } from "../animation/use-dog-house-playback";
import { DOG_HOUSE_SCENARIOS } from "../dev/scenarios";
import { DogHouseGrid } from "./dog-house-grid";
import { BonusPickGrid, LineWinLabel } from "./animation-overlays";
type LabScenario=(typeof DOG_HOUSE_SCENARIOS)[number];
export function DogHouseAnimationLab(){const [speed,setSpeed]=useState<DogHouseSpeed>("normal"),[reduced,setReduced]=useState(false),[selected,setSelected]=useState<LabScenario>(DOG_HOUSE_SCENARIOS[0]),sound=useCallback(()=>{},[]),complete=useCallback(()=>{},[]),playback=useDogHousePlayback({speed,reducedMotion:reduced,onSound:sound,onComplete:complete}),model=playback.view.model??createDisplayModel(selected.round.result.base,{roundId:selected.round.id,spinIndex:0});return <div className={`dogslot-screen dogslot-v2 ${playback.view.bonusMode?"is-bonus-mode":""}`}><header className="dogslot-lab-head"><div><small>Development only</small><h1>Casa degli Sposi Lab</h1></div><div><button onClick={()=>setSpeed((value)=>value==="normal"?"quick":value==="quick"?"turbo":"normal")}>{speed}</button><button onClick={()=>setReduced((value)=>!value)}>{reduced?"Reduced ✓":"Reduced"}</button></div></header><main className="dogslot-lab-main"><section><div className="dogslot-machine"><DogHouseGrid model={model} stoppedReels={playback.view.stoppedReels} stoppingReel={playback.view.stoppingReel} speed={speed} reducedMotion={reduced} line={playback.view.activeLine}/><LineWinLabel line={playback.view.activeLine}/></div><code>{playback.view.state}</code></section><aside>{DOG_HOUSE_SCENARIOS.map((scenario)=><button key={scenario.id} onClick={()=>{setSelected(scenario);void playback.start(scenario.round);}}>{scenario.title}</button>)}<button onClick={playback.skip}>SKIP phase / round</button></aside></main>{["revealing-free-spins","showing-free-spin-award"].includes(playback.view.state)&&playback.view.round&&<div className="dogslot-overlay"><BonusPickGrid values={playback.view.round.result.freeSpinReveal} revealed={playback.view.revealedTokens} total={playback.view.revealTotal}/></div>}</div>}
