import assert from "node:assert/strict";
import { DogHouseAnimationDirector, buildDogHouseTimeline } from "../components/slots/dog-house/animation/director.ts";
import { createDisplayModel, withWinningLine } from "../components/slots/dog-house/animation/display-reels.ts";
import { NORMAL_TIMINGS, QUICK_TIMINGS, REDUCED_TIMINGS, TURBO_TIMINGS, timingsFor } from "../components/slots/dog-house/animation/animation-config.ts";
import { runDogHouseRound } from "../domain/slots/dog-house/engine.ts";
import { createSeededRng } from "../domain/slots/sweet-lemonza/rng.ts";
import type { DogHouseSlotRound } from "../domain/models.ts";

const asRound=(seed:string):DogHouseSlotRound=>{const result=runDogHouseRound(100,createSeededRng(seed));return{id:`round-${seed}`,gameId:"casa-degli-sposi",mathVersion:result.mathVersion,userId:"test",stake:100,mode:"STANDARD",chargedAmount:100,baseWin:result.baseGamePayout,scatterWin:result.bonusScatterPayout,bonusWin:result.bonusPayout,totalWin:result.totalPayout,balanceBefore:10_000,balanceAfter:9_900+result.totalPayout,bonusTriggered:result.bonusTriggered,maxMultiplier:result.maxMultiplier,idempotencyKey:seed,result,createdAt:"2026-01-01T00:00:00.000Z"};};
const find=(predicate:(round:DogHouseSlotRound)=>boolean)=>{for(let index=0;index<10_000;index+=1){const round=asRound(`dog-animation-${index}`);if(predicate(round))return round;}throw new Error("fixture not found");};
const loss=find((round)=>round.totalWin===0),win=find((round)=>round.result.base.wins.length>0),bonus=find((round)=>round.bonusTriggered);
async function test(name:string,run:()=>void|Promise<void>){try{await run();console.log(`✓ ${name}`);}catch(error){console.error(`✗ ${name}`);throw error;}}
await test("проигрыш останавливает пять барабанов и завершается",()=>{const states=buildDogHouseTimeline(loss);assert.equal(states.filter((step)=>step.state==="stopping-reel").length,5);assert.equal(states.at(-1)?.state,"round-complete");});
await test("каждая линия проходит highlight → value → collect",()=>{const states=buildDogHouseTimeline(win),index=states.findIndex((step)=>step.state==="highlighting-line");assert.deepEqual(states.slice(index,index+3).map((step)=>step.state),["highlighting-line","showing-line-win","collecting-win"]);});
await test("бонус раскрывает ровно девять серверных значений",()=>{const steps=buildDogHouseTimeline(bonus),tokens=steps.filter((step)=>step.state==="revealing-free-spins");assert.equal(tokens.length,9);assert.deepEqual(tokens.map((step)=>step.tokenValue),bonus.result.freeSpinReveal);assert.ok(steps.some((step)=>step.state==="bonus-summary"));});
await test("profiles normal quick turbo reduced различаются",()=>{assert.deepEqual(timingsFor("normal"),NORMAL_TIMINGS);assert.deepEqual(timingsFor("quick"),QUICK_TIMINGS);assert.deepEqual(timingsFor("turbo"),TURBO_TIMINGS);assert.deepEqual(timingsFor("normal",true),REDUCED_TIMINGS);assert.ok(TURBO_TIMINGS.minimumSpin<QUICK_TIMINGS.minimumSpin&&QUICK_TIMINGS.minimumSpin<NORMAL_TIMINGS.minimumSpin);});
await test("director воспроизводит состояния строго последовательно",async()=>{const expected=buildDogHouseTimeline(loss).map((step)=>step.state),seen:string[]=[];const director=new DogHouseAnimationDirector({speed:"turbo",wait:async()=>{}});await director.playRound(loss,{onStep:(step)=>{seen.push(step.state);},onComplete:()=>{}});assert.deepEqual(seen,expected);});
await test("skip current сохраняет lifecycle, skip end приводит к round-complete",async()=>{const seen:string[]=[];const director=new DogHouseAnimationDirector({speed:"turbo",wait:async()=>{}});let first=true;await director.playRound(win,{onStep:(step)=>{seen.push(step.state);if(first&&step.state==="spinning"){first=false;director.skipToRoundEnd();}},onComplete:(kind)=>assert.equal(kind,"skipped")});assert.equal(seen.at(-1),"round-complete");});
await test("dispose отменяет playback без complete",async()=>{let completed=false,started=false;const director=new DogHouseAnimationDirector();const playing=director.playRound(loss,{onStep:(step)=>{if(step.state==="starting-reels"){started=true;director.dispose();}},onComplete:()=>{completed=true;}});while(!started)await Promise.resolve();await playing;assert.equal(completed,false);});
await test("Sticky Wild сохраняет animationId между free spins",()=>{const spins=bonus.result.freeSpins;const target=spins.findIndex((spin)=>spin.stickyWilds.length>0);if(target<0)return;const first=createDisplayModel(spins[target],{roundId:bonus.id,spinIndex:target+1}),next=spins[target+1]?createDisplayModel(spins[target+1],{roundId:bonus.id,spinIndex:target+2,previousSticky:first.stickyIds}):first;for(const [index,id] of first.stickyIds)if(next.stickyIds.has(index))assert.equal(next.stickyIds.get(index),id);});
await test("подсветка линии не меняет animationId",()=>{const model=createDisplayModel(win.result.base,{roundId:win.id,spinIndex:0}),highlighted=withWinningLine(model,win.result.base.wins[0].positions);assert.deepEqual(highlighted.cells.map((cell)=>cell.animationId),model.cells.map((cell)=>cell.animationId));});
console.log("Все проверки Casa degli Sposi Animation Director пройдены.");
