import type { DogHouseSoundEvent } from "./sound-events";
type Tone={frequency:number;end?:number;duration:number;volume:number;type:OscillatorType;delay?:number};
export class DogHouseSoundManagerV2{
  private context?:AudioContext;private muted=false;private hidden=false;private voices=0;private ambientVolume=.5;private sfxVolume=.72;private anticipationTimer?:number;private anticipationStep=0;
  constructor(){if(typeof document!=="undefined"){this.hidden=document.hidden;document.addEventListener("visibilitychange",this.visibility);}}
  private visibility=()=>{this.hidden=document.hidden;if(this.hidden){this.stopLoops();void this.context?.suspend();}};
  setMuted(value:boolean){this.muted=value;if(value){this.stopLoops();void this.context?.suspend();}else void this.unlock();}setAmbientVolume(value:number){this.ambientVolume=Math.max(0,Math.min(1,value));}setSfxVolume(value:number){this.sfxVolume=Math.max(0,Math.min(1,value));}
  async unlock(){try{if(typeof window==="undefined")return;const AudioContextClass=window.AudioContext||(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AudioContextClass)return;this.context??=new AudioContextClass();if(!this.muted&&!this.hidden&&this.context.state==="suspended")await this.context.resume();}catch{/* Audio availability never controls gameplay. */}}
  private tone(tone:Tone,ambient=false){const context=this.context;if(!context||this.muted||this.hidden||this.voices>=12)return;const oscillator=context.createOscillator(),gain=context.createGain(),start=context.currentTime+(tone.delay??0),end=start+tone.duration,volume=tone.volume*(ambient?this.ambientVolume:this.sfxVolume);this.voices+=1;oscillator.type=tone.type;oscillator.frequency.setValueAtTime(tone.frequency,start);if(tone.end)oscillator.frequency.exponentialRampToValueAtTime(tone.end,end);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(volume,start+Math.min(.018,tone.duration/4));gain.gain.exponentialRampToValueAtTime(.0001,end);oscillator.connect(gain).connect(context.destination);oscillator.start(start);oscillator.stop(end+.01);oscillator.onended=()=>{this.voices=Math.max(0,this.voices-1);oscillator.disconnect();gain.disconnect();};}
  play(event:DogHouseSoundEvent,step=0){if(this.muted||this.hidden)return;void this.unlock().then(()=>{if(event==="anticipation"){this.startAnticipation();return;}this.stopLoops();if(event==="reel-stop")this.tone({frequency:118+step*7,end:86,duration:.1,volume:.055,type:"triangle"});else if(event==="spin-press"||event==="reels-start")this.tone({frequency:108,end:58,duration:.3,volume:.045,type:"triangle"});else if(event==="line-win")this.tone({frequency:260+step*14,end:340+step*12,duration:.2,volume:.04,type:"sine"});else if(event==="line-multiplier"||event==="sticky-lock")this.tone({frequency:174,end:330,duration:.34,volume:.05,type:"triangle"});else if(event==="token-flip")this.tone({frequency:220+step*8,end:290+step*10,duration:.15,volume:.038,type:"triangle"});else if(event==="bonus-trigger"||event==="free-spins-awarded"||event==="big-win"){[196,247,294,392].forEach((frequency,index)=>this.tone({frequency,duration:index===3?.58:.24,volume:.04,type:"triangle",delay:index*.09}));}else if(event==="bonus-summary"){[392,330,262,392].forEach((frequency,index)=>this.tone({frequency,duration:.25,volume:.035,type:"sine",delay:index*.08}));}else this.tone({frequency:190+step*7,end:240+step*8,duration:.14,volume:.03,type:"sine"});}).catch(()=>undefined);}
  private startAnticipation(){this.stopLoops();this.anticipationStep=0;const pulse=()=>{const step=this.anticipationStep++,frequency=Math.min(196,104+step*7);this.tone({frequency,end:Math.max(82,frequency-18),duration:.16,volume:.032,type:"triangle"},true);this.anticipationTimer=window.setTimeout(pulse,Math.max(145,315-step*14));};pulse();}
  stopLoops(){if(this.anticipationTimer!==undefined){window.clearTimeout(this.anticipationTimer);this.anticipationTimer=undefined;}this.anticipationStep=0;}
  diagnostics(){return{activeVoices:this.voices,activeLoops:this.anticipationTimer===undefined?0:1,contextState:this.context?.state??"unavailable"};}
  dispose(){this.stopLoops();if(typeof document!=="undefined")document.removeEventListener("visibilitychange",this.visibility);void this.context?.close();}
}
