"use client";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { createClientRequestId } from "@/lib/client-id";
import { formatLira } from "@/domain/market";
import { DOG_HOUSE_PAYLINES, DOG_HOUSE_SYMBOLS } from "@/domain/slots/dog-house/config";
import type { DogHouseOperationalSettings, DogHouseSlotRound } from "@/domain/models";
import type { DogHouseCell, DogHouseSpin } from "@/domain/slots/dog-house/types";
import { DogHouseSymbolIcon } from "./dog-house-symbol";
import { DogHouseSoundManager } from "./dog-house-sound";

type InitialState={settings:DogHouseOperationalSettings;balance:number;history:DogHouseSlotRound[]};
type Phase="idle"|"requesting"|"dropping"|"result"|"bonus-intro"|"bonus-reveal"|"free-spin"|"bonus-summary";
const PREVIEW:DogHouseCell["symbol"][]=["TEN","K","BONE","Q","DACHSHUND","A","PUG","COLLAR","J","BELLA","TEN","BRUNO","K","Q","BONE"];
const previewGrid=PREVIEW.map((symbol,index)=>({id:-index-1,symbol} as DogHouseCell));
const wait=(ms:number)=>new Promise<void>((resolve)=>window.setTimeout(resolve,ms));
const SPIN_STRIPS:DogHouseCell[][]=[
  ["TEN","BRUNO","Q","BONUS","BONE","DACHSHUND"].map((symbol,index)=>({id:-100-index,symbol} as DogHouseCell)),
  ["K","BELLA","WILD","COLLAR","J","PUG"].map((symbol,index)=>symbol==="WILD"?{id:-200-index,symbol,multiplier:2}:{id:-200-index,symbol} as DogHouseCell),
  ["A","BONUS","DACHSHUND","WILD","BONE","BRUNO"].map((symbol,index)=>symbol==="WILD"?{id:-300-index,symbol,multiplier:3}:{id:-300-index,symbol} as DogHouseCell),
  ["Q","PUG","COLLAR","WILD","TEN","BELLA"].map((symbol,index)=>symbol==="WILD"?{id:-400-index,symbol,multiplier:2}:{id:-400-index,symbol} as DogHouseCell),
  ["J","BONE","BRUNO","BONUS","K","DACHSHUND"].map((symbol,index)=>({id:-500-index,symbol} as DogHouseCell)),
];

function SpinningReel({reel,settling,turbo}:{reel:number;settling:boolean;turbo:boolean}){const strip=SPIN_STRIPS[reel];return <div className={`dogslot-motion-reel ${settling?"is-settling":""}`} aria-hidden="true" style={{"--spin-speed":`${430+reel*24}ms`,"--settle-speed":turbo?"35ms":"115ms"} as React.CSSProperties}><div>{[...strip,...strip].map((cell,index)=><span key={`${cell.id}-${index}`}><DogHouseSymbolIcon cell={cell}/></span>)}</div></div>}

function Rules({stake,onClose}:{stake:number;onClose:()=>void}){const prize=(value:number)=>formatLira(Math.floor(stake*value/100));return <div className="dogslot-overlay dogslot-rules-backdrop"><section className="dogslot-rules"><header><div><small>20 линий · высокая волатильность</small><h2>Правила Casa degli Sposi</h2></div><button onClick={onClose} aria-label="Закрыть">×</button></header><div className="dogslot-rules-scroll"><p className="dogslot-rule-lead">Символы платят слева направо на соседних барабанах, начиная с первого. На каждой линии оплачивается только старшая комбинация.</p><div className="dogslot-rule-cards"><article><b>Домик Wild</b><p>Появляется только на барабанах 2, 3 и 4, заменяет любой обычный символ и несёт множитель 2X или 3X. Несколько Wild на линии складываются.</p></article><article><b>Бонусная лапа</b><p>По одной лапе на барабанах 1, 3 и 5 платят 5X ставки и запускают фриспины.</p></article><article><b>9–27 фриспинов</b><p>Перед бонусом девять жетонов открывают по 1, 2 или 3 вращения. Их значения складываются.</p></article><article><b>Sticky Wild</b><p>Каждый Wild во фриспинах остаётся в своей позиции и сохраняет множитель до конца бонуса. Retrigger отсутствует.</p></article></div><section className="dogslot-paytable"><div className="dogslot-pay-head"><b>Таблица выплат</b><small>при ставке {formatLira(stake)}</small></div><div>{DOG_HOUSE_SYMBOLS.map((item,index)=><article key={item.id}><span><DogHouseSymbolIcon cell={{id:-900-index,symbol:item.id}}/><b>{item.title}</b></span><div><em>5 · {prize(item.payouts[2])}</em><em>4 · {prize(item.payouts[1])}</em><em>3 · {prize(item.payouts[0])}</em></div></article>)}</div></section><details><summary>20 выигрышных линий</summary><div className="dogslot-lines">{DOG_HOUSE_PAYLINES.map((line,index)=><span key={index}><b>{index+1}</b>{line.map((row,reel)=><i key={reel} style={{gridRow:row+1,gridColumn:reel+1}}/>)}</span>)}</div></details><p className="dogslot-disclaimer">Только виртуальные свадебные лиры. Самостоятельная игровая математика и оригинальные SVG-ассеты.</p></div></section></div>}

function History({rounds,onClose}:{rounds:DogHouseSlotRound[];onClose:()=>void}){return <div className="dogslot-overlay"><section className="dogslot-sheet"><header><h2>Последние Spin</h2><button onClick={onClose}>×</button></header>{rounds.length?rounds.map((round)=><div className="dogslot-history-row" key={round.id}><span>{new Date(round.createdAt).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})}</span><b>{formatLira(round.stake)}</b><strong className={round.totalWin>0?"is-win":""}>{round.totalWin>0?`+${formatLira(round.totalWin)}`:"0"}</strong></div>):<p className="p-8 text-center text-sm">История пока пуста.</p>}</section></div>}

export function DogHouseGame({initialState}:{initialState:InitialState}){
  const bets=initialState.settings.allowedBets,[stake,setStake]=useState(bets[0]),[balance,setBalance]=useState(initialState.balance),[history,setHistory]=useState(initialState.history),[grid,setGrid]=useState<DogHouseCell[]>(previewGrid),[spinView,setSpinView]=useState<DogHouseSpin>(),[phase,setPhase]=useState<Phase>("idle"),[round,setRound]=useState<DogHouseSlotRound>(),[serverBalance,setServerBalance]=useState<number>(),[freeIndex,setFreeIndex]=useState(0),[turbo,setTurbo]=useState(false),[rules,setRules]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[error,setError]=useState(""),[stoppedReels,setStoppedReels]=useState(5),[settlingReel,setSettlingReel]=useState(-1),[activeWin,setActiveWin]=useState(-1),[revealedTokens,setRevealedTokens]=useState(0),[revealTotal,setRevealTotal]=useState(0),[bonusReady,setBonusReady]=useState(false),[muted,setMuted]=useState(false),[newSticky,setNewSticky]=useState<Set<number>>(new Set()),[previousSticky,setPreviousSticky]=useState<Set<number>>(new Set()),[bonusActive,setBonusActive]=useState(false),[sound]=useState(()=>new DogHouseSoundManager());
  const mounted=useRef(true),playingBonus=useRef(false),revealingBonus=useRef(false),stickyRef=useRef(new Set<number>());
  useEffect(()=>()=>{mounted.current=false;sound.dispose();},[sound]);
  const busy=phase!=="idle",winningPositions=useMemo(()=>new Set(activeWin>=0?(spinView?.wins[activeWin]?.positions??[]):(spinView?.wins.flatMap((win)=>win.positions)??[])),[spinView,activeWin]);

  async function presentWins(spin:DogHouseSpin){
    if(spin.wins.length===0){setActiveWin(-1);return;}
    for(let index=0;index<spin.wins.length;index+=1){if(!mounted.current)return;setActiveWin(index);sound.play("line-win",Math.min(index,4));await wait(turbo?95:260);}
    setActiveWin(-1);
  }

  async function revealSpin(spin:DogHouseSpin,nextPhase:"result"|"free-spin"){
    setGrid(spin.grid);setSpinView(undefined);setStoppedReels(0);setSettlingReel(-1);setActiveWin(-1);setPhase("dropping");if(nextPhase==="free-spin")sound.play("free-spin");
    let pawCount=0;
    for(let reel=0;reel<5;reel+=1){if(!mounted.current)return;await wait(turbo?50:105);setSettlingReel(reel);await wait(turbo?35:115);if(!mounted.current)return;setStoppedReels(reel+1);setSettlingReel(-1);sound.play("reel-stop",reel);const hasPaw=[0,1,2].some((row)=>spin.grid[row*5+reel]?.symbol==="BONUS");if(hasPaw){pawCount+=1;sound.play("paw",pawCount);if(pawCount===2)sound.play("anticipation");}}
    const nextSticky=new Set(spin.stickyWilds.map((wild)=>wild.index)),landed=new Set([...nextSticky].filter((index)=>!stickyRef.current.has(index)));setNewSticky(landed);stickyRef.current=nextSticky;setPreviousSticky(nextSticky);setSpinView(spin);setPhase(nextPhase);if(landed.size)sound.play("wild-lock");if(spin.bonusCount===3)sound.play("bonus-trigger");await presentWins(spin);if(mounted.current)setNewSticky(new Set());
  }
  async function finish(targetBalance:number,nextRound:DogHouseSlotRound){if(!mounted.current)return;setBalance(targetBalance);setHistory((current)=>[nextRound,...current.filter((item)=>item.id!==nextRound.id)].slice(0,20));setPhase("idle");setFreeIndex(0);setBonusActive(false);setPreviousSticky(new Set());stickyRef.current=new Set();}
  async function playBonus(nextRound:DogHouseSlotRound,targetBalance:number){if(playingBonus.current||!bonusReady)return;playingBonus.current=true;setBonusActive(true);stickyRef.current=new Set();setPreviousSticky(new Set());for(let index=0;index<nextRound.result.freeSpins.length;index+=1){if(!mounted.current)return;setFreeIndex(index+1);await revealSpin(nextRound.result.freeSpins[index],"free-spin");if(index<nextRound.result.freeSpins.length-1)await wait(turbo?80:240);}playingBonus.current=false;if(!mounted.current)return;sound.play("bonus-summary");setPhase("bonus-summary");setServerBalance(targetBalance);}
  async function revealBonus(nextRound:DogHouseSlotRound){if(revealingBonus.current)return;revealingBonus.current=true;setPhase("bonus-reveal");setRevealedTokens(0);setRevealTotal(0);setBonusReady(false);let total=0;for(let index=0;index<nextRound.result.freeSpinReveal.length;index+=1){await wait(turbo?65:170);if(!mounted.current)return;total+=nextRound.result.freeSpinReveal[index];setRevealedTokens(index+1);setRevealTotal(total);sound.play("token-reveal",nextRound.result.freeSpinReveal[index]);}await wait(turbo?80:240);if(!mounted.current)return;setBonusReady(true);revealingBonus.current=false;sound.play("bonus-ready");}
  async function spin(){if(busy)return;if(!navigator.onLine){setError("Spin требует соединения с сервером.");return;}if(balance<stake){setError("Недостаточно свадебных лир.");return;}void sound.unlock();sound.play("spin");setBonusActive(false);setPreviousSticky(new Set());setError("");setBalance((value)=>value-stake);setSpinView(undefined);setStoppedReels(0);setSettlingReel(-1);setPhase("dropping");try{const response=await fetch("/api/slots/casa-degli-sposi/spin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({gameId:"casa-degli-sposi",stake,idempotencyKey:createClientRequestId()})}),body=await response.json() as {round?:DogHouseSlotRound;balance?:number;error?:string};if(!response.ok||!body.round||body.balance===undefined)throw new Error(body.error??"Spin не выполнен");const nextRound=body.round;setRound(nextRound);stickyRef.current=new Set();await revealSpin(nextRound.result.base,"result");if(nextRound.bonusTriggered){setPhase("bonus-intro");setServerBalance(body.balance);}else await finish(body.balance,nextRound);}catch(cause){setBalance((value)=>value+stake);setSettlingReel(-1);setPhase("idle");setError(cause instanceof Error?cause.message:"Spin не выполнен");}}
  function changeStake(direction:number){const index=bets.indexOf(stake),next=bets[Math.max(0,Math.min(bets.length-1,index+direction))];setStake(next);}
  const activeLine=activeWin>=0?spinView?.wins[activeWin]:undefined;
  return <div className={`dogslot-screen ${bonusActive?"is-bonus-mode":""}`}><div className="dogslot-sky"/><header className="dogslot-top"><Link href="/slots" aria-label="Назад">←</Link><div><span>₤</span>{balance.toLocaleString("ru-RU")}</div><nav><button onClick={()=>{setMuted((value)=>{sound.setMuted(!value);return !value;});}} aria-label={muted?"Включить звук":"Выключить звук"}>{muted?"♩":"♫"}</button><button onClick={()=>setRules(true)}>?</button><button onClick={()=>setHistoryOpen(true)}>≡</button></nav></header><main><div className="dogslot-title"><small>Lucky Wedding Dogs</small><h1>Casa degli <b>Sposi</b></h1></div><div className={`dogslot-machine is-${phase}`}><div className="dogslot-reels">{[0,1,2,3,4].map((reel)=><div className="dogslot-reel" key={reel}><div className="dogslot-reel-result">{[0,1,2].map((row)=>{const index=row*5+reel,cell=grid[index],isWild=bonusActive&&cell.symbol==="WILD",isSticky=isWild&&(phase!=="dropping"||previousSticky.has(index)),landing=phase==="dropping"&&reel===settlingReel;return <div key={isWild?`sticky-${index}`:`${cell.id}`} className={`dogslot-cell ${winningPositions.has(index)?"is-winning":""} ${isSticky?"is-sticky":""} ${newSticky.has(index)?"is-new-sticky":""} ${landing?"is-landing":""}`}><DogHouseSymbolIcon cell={cell}/></div>})}</div>{phase==="dropping"&&reel>=stoppedReels&&<SpinningReel reel={reel} settling={settlingReel===reel} turbo={turbo}/>}</div>)}</div></div><div className="dogslot-status" aria-live="polite">{phase==="free-spin"&&round&&<span>ФРИСПИН {freeIndex}/{round.result.awardedFreeSpins}</span>}{activeLine?<strong>ЛИНИЯ {activeLine.line} · {formatLira(activeLine.payout)}{activeLine.wildMultiplier>1?` · ${activeLine.wildMultiplier}X`:""}</strong>:spinView&&spinView.payout>0&&<strong>ВЫИГРЫШ · {formatLira(spinView.payout)}</strong>}{error&&<b>{error}</b>}</div></main><footer className="dogslot-controls"><div className="dogslot-bet"><button disabled={busy||bets.indexOf(stake)===0} onClick={()=>changeStake(-1)}>−</button><span><small>Ставка</small><b>{formatLira(stake)}</b></span><button disabled={busy||bets.indexOf(stake)===bets.length-1} onClick={()=>changeStake(1)}>+</button></div><button className="dogslot-spin" disabled={busy} onClick={()=>void spin()}><b>SPIN</b><small>{formatLira(stake)}</small></button><button className={`dogslot-turbo ${turbo?"is-active":""}`} onClick={()=>setTurbo((value)=>!value)}><b>⚡</b><small>Turbo</small></button></footer>
  {rules&&<Rules stake={stake} onClose={()=>setRules(false)}/>} {historyOpen&&<History rounds={history} onClose={()=>setHistoryOpen(false)}/>} {(phase==="bonus-intro"||phase==="bonus-reveal")&&round&&<button className={`dogslot-overlay dogslot-bonus-intro ${phase==="bonus-reveal"?"is-revealing":""}`} onClick={()=>phase==="bonus-intro"?void revealBonus(round):bonusReady?void playBonus(round,serverBalance!):undefined}><span>БОНУСНАЯ ЛАПА</span><strong>{phase==="bonus-intro"?"?":revealTotal}</strong><b>{phase==="bonus-intro"?"ОТКРОЙТЕ ФРИСПИНЫ":"ФРИСПИНОВ"}</b><small>{phase==="bonus-intro"?"Нажмите, чтобы открыть девять жетонов":bonusReady?"Нажмите, чтобы начать":"Лапы складывают количество вращений"}</small><div>{round.result.freeSpinReveal.map((value,index)=><i className={index<revealedTokens?"is-open":""} key={index}><span>🐾</span><b>{index<revealedTokens?value:""}</b></i>)}</div></button>} {phase==="bonus-summary"&&round&&<button className="dogslot-overlay dogslot-summary" onClick={()=>void finish(serverBalance!,round)}><span>СОБАЧЬЯ ВЕЧЕРИНКА</span><strong>{formatLira(round.totalWin)}</strong><b>Общий выигрыш</b><small>Нажмите, чтобы забрать</small></button>}
  </div>;
}
