import { AdminLemonzaSettings } from "@/components/admin-lemonza-settings";
import { formatLira } from "@/domain/market";
import { getSweetLemonzaAdminState, listUsers } from "@/infrastructure/mock/store";

export default async function AdminSlotsPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const {q}=await searchParams, state=getSweetLemonzaAdminState(q), users=listUsers();
  const name=(id:string)=>users.find((user)=>user.id===id)?.displayName??"—";
  return <div><p className="eyebrow">La sala giochi</p><h1 className="serif mt-1 text-3xl font-bold">Sweet Lemonza</h1><p className="mt-2 text-sm text-[#6f7a72]">Результаты завершённых раундов неизменяемы. Каждый сохраняет mathVersion и серверный сценарий.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Раунды",state.analytics.rounds],["Оборот",formatLira(state.analytics.totalStake)],["Выигрыши",formatLira(state.analytics.totalWin)],["Фактический RTP",`${(state.analytics.actualRtp*100).toFixed(2)}%`],["Частота бонуса",`${(state.analytics.bonusFrequency*100).toFixed(2)}%`]].map(([label,value])=><div className="card p-4" key={label}><span className="text-xs font-bold text-[#788078]">{label}</span><strong className="serif mt-1 block text-2xl">{value}</strong></div>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-[20rem_1fr]"><AdminLemonzaSettings initial={state.settings}/><section className="card overflow-hidden"><form className="flex gap-2 border-b border-[#174b38]/10 p-4"><input name="q" defaultValue={q} className="input" placeholder="Round ID"/><button className="btn-secondary">Найти</button></form><div className="overflow-x-auto"><table className="w-full min-w-[55rem] text-left text-xs"><thead className="bg-[#174b38] text-white/70"><tr><th className="p-3">Round</th><th className="p-3">Гость</th><th className="p-3">Режим</th><th className="p-3">Стоимость</th><th className="p-3">Выигрыш</th><th className="p-3">Бонус</th><th className="p-3">Math</th></tr></thead><tbody>{state.rounds.map((round)=><tr key={round.id} className="border-b border-[#174b38]/8"><td className="max-w-40 truncate p-3 font-mono" title={round.id}>{round.id}</td><td className="p-3 font-bold">{name(round.userId)}</td><td className="p-3">{round.mode??"STANDARD"}</td><td className="p-3">{formatLira(round.chargedAmount??round.stake)}</td><td className="p-3 font-bold">{formatLira(round.totalWin)}</td><td className="p-3">{round.bonusTriggered?"Да":"Нет"}</td><td className="p-3">{round.mathVersion}</td></tr>)}</tbody></table>{!state.rounds.length&&<p className="p-8 text-center text-sm text-[#788078]">Раундов пока нет.</p>}</div></section></div></div>;
}
