"use client";
import { memo, useEffect, useRef } from "react";
import type { CSSProperties } from "react";
import { LemonzaSymbolIcon } from "../../lemonza-symbol";
import type { DisplaySymbol } from "../animation/display-grid";
import type { GameAnimationState } from "../animation/states";
import type { ParticleLayerHandle } from "./particle-layer";
import { ParticleLayer } from "./particle-layer";

export const GameGrid=memo(function GameGrid({symbols,state,cascadeIndex,reducedMotion,shake=false,onParticleCount}:{symbols:DisplaySymbol[];state:GameAnimationState;cascadeIndex:number;reducedMotion:boolean;shake?:boolean;onParticleCount?:(count:number)=>void}){
  const particles=useRef<ParticleLayerHandle>(null),burstKey=useRef("");
  useEffect(()=>{if(state==="collapsing-grid"){particles.current?.clear();onParticleCount?.(0);return;}if(state!=="removing-symbols")return;const winning=symbols.filter((symbol)=>symbol.isRemoving),key=winning.map((symbol)=>symbol.animationId).join("-");if(!winning.length||key===burstKey.current)return;burstKey.current=key;particles.current?.burst(winning.map((symbol)=>({row:symbol.row,column:symbol.column,symbol:symbol.cell.symbol,intensity:Math.min(1.45,1+cascadeIndex*.08)})));onParticleCount?.(particles.current?.active()??0);},[state,symbols,cascadeIndex,onParticleCount]);
  const columns=Array.from({length:6},(_,column)=>symbols.filter((symbol)=>symbol.column===column));
  return <div className={`lemonza-grid-stage ${state} ${shake&&!reducedMotion?"lemonza-shake":""}`} data-animation-state={state}><div className="lemonza-grid-surface" role="grid" aria-label={`Игровая сетка. Фаза: ${state}`}>
    {columns.map((columnSymbols,column)=>{const visible=columnSymbols.filter((symbol)=>!symbol.isQueued),fullRefill=state==="dropping-new-symbols"&&visible.length>0&&visible.every((symbol)=>symbol.isNew),columnStyle={"--column-x":`${column*100}%`,"--column-initial-delay":`${column*40}ms`,"--column-refill-delay":`${column*20}ms`,"--column-delay-turbo":`${column*14}ms`,"--column-exit-delay":`${column*10}ms`,"--column-exit-delay-turbo":`${column*3}ms`} as CSSProperties;return <div key={column} style={columnStyle} className={`lemonza-column ${fullRefill?"is-full-refill":""}`} data-column={column}>{columnSymbols.map((symbol)=>{const y=`${symbol.row*100}%`,previousY=`${(symbol.previousRow??symbol.row-symbol.dropDistance)*100}%`,style={"--slot-row":symbol.row,"--slot-column":symbol.column,"--slot-y":y,"--slot-start-y":previousY,"--slot-previous-y":previousY,"--slot-bounce-y":`${(symbol.row+.055)*100}%`,"--slot-collapse-bounce-y":`${(symbol.row+.045)*100}%`,"--slot-refill-delay":`${(symbol.column*10+symbol.stableVariation*4)*2}ms`,"--slot-delay-turbo":`${symbol.column*14}ms`,"--collapse-duration-normal":`${(180+Math.min(symbol.dropDistance*18,72))*2}ms`,"--collapse-duration-turbo":`${(70+Math.min(symbol.dropDistance*8,32))*2}ms`,"--slot-tilt":`${symbol.stableVariation*3-1.5}deg`,"--win-delay":`${Math.min((symbol.row*6+column)*10,100)}ms`,"--win-delay-turbo":`${Math.min((symbol.row*6+column)*4,40)}ms`} as CSSProperties,moving=state==="collapsing-grid"&&!symbol.isQueued&&symbol.dropDistance>0;return <div role="gridcell" aria-hidden={symbol.isQueued||undefined} key={symbol.animationId} style={style} data-animation-id={symbol.animationId} data-new={symbol.isNew||undefined} data-queued={symbol.isQueued||undefined} data-leaving={symbol.isLeaving||undefined} data-winning={symbol.isWinning||undefined} data-removing={symbol.isRemoving||undefined} data-moving={moving||undefined} data-multiplier={symbol.isMultiplier||undefined} data-scatter={symbol.isScatter||undefined} data-collecting-multiplier={symbol.isCollectingMultiplier||undefined} className={`lemonza-tile ${symbol.isNew?"is-new":""} ${symbol.isQueued?"is-queued":""} ${symbol.isLeaving?"is-leaving":""} ${symbol.isWinning?"is-winning":""} ${symbol.isRemoving?"is-removing":""} ${moving?"is-moving":""} ${symbol.isMultiplier?"is-multiplier":""} ${symbol.isScatter?"is-scatter":""} ${symbol.isCollectingMultiplier?"is-collecting-multiplier":""}`}><div className="lemonza-tile-face"><LemonzaSymbolIcon cell={symbol.cell} className="h-full w-full"/><span className="lemonza-shine"/></div></div>;})}</div>;})}
    <ParticleLayer ref={particles} reducedMotion={reducedMotion}/>
  </div></div>;
});
